;; suki WASM mixer kernel — AudioWorklet + WebAssembly anti-explosion core.
;; Key-sound formula (rate-independent, x in SECONDS):
;;   E   = min(500x,1)·exp(-2.6x)         attack + body decay
;;   y   = a0·E·( sin(w)+.4sin(2w)+.2sin(3w)+.1sin(4w)
;;               +.38sin(1.004w)+.16sin(2.008w)+.08sin(3.012w) ) + thump
;;   w   = 2pi·f·x  (f = 440·2^((midi-69)/12), bent);  a0 = .49·vel
;;   thump = .05·noise·exp(-900x);  key-up release exp(-LN2/(.16·sr))
;; Memory layout (stride 16 f64/voice) MUST match the JS side:
;;   F64B 8 (8192x16), I32B 1048584, SUSP 1310728, BFP 1310792,
;;   NZP 1310920, SEEDP 1310936, OUTL 1310944, OUTR 1343712 (22 pages)
(module
  (memory (export "memory") 22 22)

  (func $P (param $r f64) (result f64)
    (local $r2 f64)
    (local.set $r2 (f64.mul (local.get $r) (local.get $r)))
    (f64.add
      (local.get $r)
      (f64.mul
        (f64.mul (local.get $r) (local.get $r2))
        (f64.add (f64.const -0.16666666641626524)
          (f64.mul (local.get $r2)
            (f64.add (f64.const 0.008333329385889463)
              (f64.mul (local.get $r2)
                (f64.add (f64.const -0.00019839334836096632)
                  (f64.mul (local.get $r2)
                    (f64.add (f64.const 0.000002718311493989822)
                      (f64.mul (local.get $r2) (f64.const -1.6072539123367897e-8))))))))))))

  (func $sinw (param $x f64) (result f64)
    (local $y f64)
    (local.set $x
      (f64.sub (local.get $x)
        (f64.mul (f64.floor (f64.mul (local.get $x) (f64.const 0.15915494309189535)))
                 (f64.const 6.283185307179586))))
    (if (f64.lt (local.get $x) (f64.const 1.5707963267948966))
      (then (return (call $P (local.get $x)))))
    (if (f64.lt (local.get $x) (f64.const 3.141592653589793))
      (then (return (call $P (f64.sub (f64.const 3.141592653589793) (local.get $x))))))
    (if (f64.lt (local.get $x) (f64.const 4.71238898038469))
      (then
        (local.set $y (f64.sub (local.get $x) (f64.const 3.141592653589793)))
        (return (f64.neg (call $P (local.get $y))))
      ))
    (local.set $y (f64.sub (f64.const 6.283185307179586) (local.get $x)))
    (f64.neg (call $P (local.get $y))))

  (func $mix (export "mix")
    (param $f64b i32) (param $i32b i32) (param $susp i32) (param $bfp i32)
    (param $nzp i32) (param $seedp i32) (param $outl i32) (param $outr i32)
    (param $n i32) (param $cs0 f64) (param $step f64) (param $vp i32)
    (param $sr f64) (param $tau f64) (param $kill f64) (param $stereo i32)
    (local $v i32) (local $vi i32) (local $c i32) (local $fb i32) (local $k i32)
    (local $live i32) (local $stv i32) (local $holdv i32) (local $at0 i32) (local $rt i32)
    (local $chi i32) (local $susv i32) (local $ppv i32) (local $dead i32) (local $rel i32) (local $eng i32)
    (local $a f64) (local $na f64) (local $kd f64) (local $kn f64) (local $kr f64) (local $knr f64)
    (local $freq f64) (local $a0 f64) (local $p1 f64) (local $p2 f64) (local $p3 f64) (local $p4 f64)
    (local $p5 f64) (local $p6 f64) (local $p7 f64)
    (local $d f64) (local $d2 f64) (local $d3 f64) (local $d4 f64) (local $d5 f64) (local $d6 f64) (local $d7 f64)
    (local $att f64) (local $fl f64) (local $g f64)
    (local $cs f64) (local $y f64) (local $t f64) (local $w f64) (local $ny f64) (local $s2 i32)
    (local $ns i32) (local $nzlp f64) (local $ad i32)
    (local.set $ns (i32.load (local.get $seedp)))
    (local.set $nzlp (f64.load (local.get $nzp)))
    (local.set $s2 (i32.const 0))
    (block $zdone (loop $z
      (br_if $zdone (i32.ge_s (local.get $s2) (local.get $n)))
      (f32.store (i32.add (local.get $outl) (i32.shl (local.get $s2) (i32.const 2))) (f32.const 0))
      (f32.store (i32.add (local.get $outr) (i32.shl (local.get $s2) (i32.const 2))) (f32.const 0))
      (local.set $s2 (i32.add (local.get $s2) (i32.const 1)))
      (br $z)))
    (local.set $v (i32.const 0))
    (block $vdone (loop $voices
      (br_if $vdone (i32.ge_s (local.get $v) (local.get $vp)))
      (local.set $vi (local.get $v))
      (local.set $c (i32.add (local.get $i32b) (i32.shl (local.get $vi) (i32.const 5))))
      (local.set $live (i32.load (local.get $c)))
      (local.set $v (i32.add (local.get $v) (i32.const 1)))
      (br_if $voices (i32.eqz (local.get $live)))
      (local.set $stv   (i32.load (i32.add (local.get $c) (i32.const 4))))
      (local.set $holdv (i32.load (i32.add (local.get $c) (i32.const 8))))
      (local.set $at0   (i32.load (i32.add (local.get $c) (i32.const 12))))
      (local.set $rt    (i32.load (i32.add (local.get $c) (i32.const 16))))
      (local.set $chi   (i32.load (i32.add (local.get $c) (i32.const 20))))
      (local.set $ppv   (i32.load (i32.add (local.get $c) (i32.const 24))))
      (local.set $eng   (i32.load (i32.add (local.get $c) (i32.const 28))))
      (local.set $fb (i32.add (local.get $f64b) (i32.mul (local.get $vi) (i32.const 128))))
      (local.set $a    (f64.load (local.get $fb)))
      (local.set $na   (f64.load (i32.add (local.get $fb) (i32.const 8))))
      (local.set $kd   (f64.load (i32.add (local.get $fb) (i32.const 16))))
      (local.set $kn   (f64.load (i32.add (local.get $fb) (i32.const 24))))
      (local.set $kr   (f64.load (i32.add (local.get $fb) (i32.const 32))))
      (local.set $knr  (f64.load (i32.add (local.get $fb) (i32.const 40))))
      (local.set $p1   (f64.load (i32.add (local.get $fb) (i32.const 48))))
      (local.set $p2   (f64.load (i32.add (local.get $fb) (i32.const 56))))
      (local.set $p3   (f64.load (i32.add (local.get $fb) (i32.const 64))))
      (local.set $p4   (f64.load (i32.add (local.get $fb) (i32.const 72))))
      (local.set $p5   (f64.load (i32.add (local.get $fb) (i32.const 80))))
      (local.set $p6   (f64.load (i32.add (local.get $fb) (i32.const 88))))
      (local.set $p7   (f64.load (i32.add (local.get $fb) (i32.const 96))))
      (local.set $freq (f64.load (i32.add (local.get $fb) (i32.const 104))))
      (local.set $a0   (f64.load (i32.add (local.get $fb) (i32.const 112))))
      (local.set $g    (f64.load (i32.add (local.get $fb) (i32.const 120))))
      (local.set $d (f64.div
        (f64.mul (f64.mul (local.get $tau) (local.get $freq))
                 (f64.load (i32.add (local.get $bfp) (i32.shl (local.get $chi) (i32.const 3)))))
        (local.get $sr)))
      (local.set $susv (i32.load (i32.add (local.get $susp) (i32.shl (local.get $chi) (i32.const 2)))))
      (local.set $cs (local.get $cs0))
      (local.set $s2 (i32.const 0))
      (local.set $dead (i32.const 0))
      ;; ============ percussion voice (unchanged model) ============
      (if (i32.ne (local.get $ppv) (i32.const 0))
        (then
          (local.set $fl (f64.mul (local.get $a0) (f64.const 0.3)))
          (block $pexit (loop $ploop
            (br_if $pexit (i32.ge_s (local.get $s2) (local.get $n)))
            (local.set $k (local.get $s2))
            (local.set $s2 (i32.add (local.get $s2) (i32.const 1)))
            (local.set $cs (f64.add (local.get $cs) (local.get $step)))
            (if (i32.eqz (local.get $stv))
              (then
                (if (f64.lt (local.get $cs) (f64.convert_i32_s (local.get $at0)))
                  (then (br $ploop))
                  (else (local.set $stv (i32.const 1))))))
            (if (i32.and (f64.ge (local.get $cs) (f64.convert_i32_s (local.get $rt)))
                         (i32.eqz (local.get $holdv)))
              (then
                (if (i32.ne (local.get $susv) (i32.const 0))
                  (then (local.set $holdv (i32.const 1)))
                  (else
                    (local.set $kd (local.get $kr))
                    (local.set $kn (local.get $knr))))))
            (local.set $a (f64.mul (local.get $a) (local.get $kd)))
            (local.set $na (f64.mul (local.get $na) (local.get $kn)))
            (if (f64.lt (f64.add (local.get $a) (local.get $na)) (local.get $kill))
              (then (local.set $dead (i32.const 1)) (br $pexit)))
            (local.set $ns (i32.xor (local.get $ns) (i32.shl (local.get $ns) (i32.const 13))))
            (local.set $ns (i32.xor (local.get $ns) (i32.shr_u (local.get $ns) (i32.const 17))))
            (local.set $ns (i32.xor (local.get $ns) (i32.shl (local.get $ns) (i32.const 5))))
            (local.set $w (f64.sub (f64.div (f64.convert_i32_u (local.get $ns)) (f64.const 2147483648))
                                   (f64.const 1)))
            (local.set $nzlp (f64.add (local.get $nzlp)
              (f64.mul (f64.sub (local.get $w) (local.get $nzlp)) (f64.const 0.42))))
            (local.set $p1 (f64.add (local.get $p1) (local.get $d)))
            (if (f64.gt (local.get $p1) (local.get $tau))
              (then (local.set $p1 (f64.sub (local.get $p1) (local.get $tau)))))
            (local.set $y (f64.mul
              (f64.add (f64.mul (call $sinw (local.get $p1)) (local.get $a))
                       (f64.mul (f64.sub (local.get $w) (local.get $nzlp)) (local.get $na)))
              (f64.const 1.35)))
            (local.set $ad (i32.add (local.get $outl) (i32.shl (local.get $k) (i32.const 2))))
            (f32.store (local.get $ad)
              (f32.add (f32.load (local.get $ad)) (f32.demote_f64 (local.get $y))))
            (if (i32.ne (local.get $stereo) (i32.const 0))
              (then
                (local.set $ad (i32.add (local.get $outr) (i32.shl (local.get $k) (i32.const 2))))
                (f32.store (local.get $ad)
                  (f32.add (f32.load (local.get $ad))
                           (f32.demote_f64 (f64.mul (local.get $y) (f64.const 0.93)))))))
            (br $ploop))))
        (else
          (if (i32.ne (local.get $eng) (i32.const 0))
          (then
          ;; ============ key-formula voice ============
          (local.set $att (f64.div (f64.const 500) (local.get $sr)))
          (local.set $d2 (f64.mul (local.get $d) (f64.const 2)))
          (local.set $d3 (f64.mul (local.get $d) (f64.const 3)))
          (local.set $d4 (f64.mul (local.get $d) (f64.const 4)))
          (local.set $d5 (f64.mul (local.get $d) (f64.const 1.004)))
          (local.set $d6 (f64.mul (local.get $d) (f64.const 2.008)))
          (local.set $d7 (f64.mul (local.get $d) (f64.const 3.012)))
          (block $texit (loop $tloop
            (br_if $texit (i32.ge_s (local.get $s2) (local.get $n)))
            (local.set $k (local.get $s2))
            (local.set $s2 (i32.add (local.get $s2) (i32.const 1)))
            (local.set $cs (f64.add (local.get $cs) (local.get $step)))
            (if (i32.eqz (local.get $stv))
              (then
                (if (f64.lt (local.get $cs) (f64.convert_i32_s (local.get $at0)))
                  (then (br $tloop))
                  (else (local.set $stv (i32.const 1))))))
            (if (i32.and (f64.ge (local.get $cs) (f64.convert_i32_s (local.get $rt)))
                         (i32.eqz (local.get $holdv)))
              (then
                (if (i32.ne (local.get $susv) (i32.const 0))
                  (then (local.set $holdv (i32.const 1)))
                  (else (local.set $kd (local.get $kr))))))
            (if (f64.lt (local.get $g) (f64.const 1))
              (then
                (local.set $g (f64.add (local.get $g) (local.get $att)))
                (if (f64.gt (local.get $g) (f64.const 1))
                  (then (local.set $g (f64.const 1))))))
            (local.set $a (f64.mul (local.get $a) (local.get $kd)))
            (if (f64.lt (f64.mul (local.get $a) (local.get $a0)) (local.get $kill))
              (then (local.set $dead (i32.const 1)) (br $texit)))
            (local.set $ny (f64.const 0))
            (if (f64.gt (local.get $na) (f64.const 1e-4))
              (then
                (local.set $na (f64.mul (local.get $na) (local.get $knr)))
                (local.set $ns (i32.xor (local.get $ns) (i32.shl (local.get $ns) (i32.const 13))))
                (local.set $ns (i32.xor (local.get $ns) (i32.shr_u (local.get $ns) (i32.const 17))))
                (local.set $ns (i32.xor (local.get $ns) (i32.shl (local.get $ns) (i32.const 5))))
                (local.set $ny (f64.mul
                  (f64.sub (f64.div (f64.convert_i32_u (local.get $ns)) (f64.const 2147483648))
                           (f64.const 1))
                  (local.get $na)))))
            (local.set $p1 (f64.add (local.get $p1) (local.get $d)))
            (if (f64.gt (local.get $p1) (local.get $tau))
              (then (local.set $p1 (f64.sub (local.get $p1) (local.get $tau)))))
            (local.set $p2 (f64.add (local.get $p2) (local.get $d2)))
            (if (f64.gt (local.get $p2) (local.get $tau))
              (then (local.set $p2 (f64.sub (local.get $p2) (local.get $tau)))))
            (local.set $p3 (f64.add (local.get $p3) (local.get $d3)))
            (if (f64.gt (local.get $p3) (local.get $tau))
              (then (local.set $p3 (f64.sub (local.get $p3) (local.get $tau)))))
            (local.set $p4 (f64.add (local.get $p4) (local.get $d4)))
            (if (f64.gt (local.get $p4) (local.get $tau))
              (then (local.set $p4 (f64.sub (local.get $p4) (local.get $tau)))))
            (local.set $p5 (f64.add (local.get $p5) (local.get $d5)))
            (if (f64.gt (local.get $p5) (local.get $tau))
              (then (local.set $p5 (f64.sub (local.get $p5) (local.get $tau)))))
            (local.set $p6 (f64.add (local.get $p6) (local.get $d6)))
            (if (f64.gt (local.get $p6) (local.get $tau))
              (then (local.set $p6 (f64.sub (local.get $p6) (local.get $tau)))))
            (local.set $p7 (f64.add (local.get $p7) (local.get $d7)))
            (if (f64.gt (local.get $p7) (local.get $tau))
              (then (local.set $p7 (f64.sub (local.get $p7) (local.get $tau)))))
            (local.set $t (call $sinw (local.get $p1)))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p2)) (f64.const 0.4))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p3)) (f64.const 0.2))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p4)) (f64.const 0.1))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p5)) (f64.const 0.38))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p6)) (f64.const 0.16))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p7)) (f64.const 0.08))))
            (local.set $y (f64.add (f64.mul (f64.mul (f64.mul (local.get $a0) (local.get $a)) (local.get $g)) (local.get $t))
                                   (local.get $ny)))
            (local.set $ad (i32.add (local.get $outl) (i32.shl (local.get $k) (i32.const 2))))
            (f32.store (local.get $ad)
              (f32.add (f32.load (local.get $ad)) (f32.demote_f64 (local.get $y))))
            (if (i32.ne (local.get $stereo) (i32.const 0))
              (then
                (local.set $ad (i32.add (local.get $outr) (i32.shl (local.get $k) (i32.const 2))))
                (f32.store (local.get $ad)
                  (f32.add (f32.load (local.get $ad))
                           (f32.demote_f64 (f64.mul (local.get $y) (f64.const 0.93)))))))
            (br $tloop)))
          )
          (else
          ;; ============ CLASSIC tonal voice (original sfx) ============
          (local.set $d2 (f64.mul (local.get $d) (f64.const 2.0007)))
          (local.set $d3 (f64.mul (local.get $d) (f64.const 3.0021)))
          (local.set $d4 (f64.mul (local.get $d) (f64.const 0.99965)))
          (local.set $fl (f64.mul (local.get $a0) (f64.const 0.3)))
          (block $cexit (loop $cloop
            (br_if $cexit (i32.ge_s (local.get $s2) (local.get $n)))
            (local.set $k (local.get $s2))
            (local.set $s2 (i32.add (local.get $s2) (i32.const 1)))
            (local.set $cs (f64.add (local.get $cs) (local.get $step)))
            (if (i32.eqz (local.get $stv))
              (then
                (if (f64.lt (local.get $cs) (f64.convert_i32_s (local.get $at0)))
                  (then (br $cloop))
                  (else (local.set $stv (i32.const 1))))))
            (if (i32.and (f64.ge (local.get $cs) (f64.convert_i32_s (local.get $rt)))
                         (i32.eqz (local.get $holdv)))
              (then
                (if (i32.ne (local.get $susv) (i32.const 0))
                  (then (local.set $holdv (i32.const 1)))
                  (else (local.set $rel (i32.const 1))
                        (local.set $kd (local.get $kr))
                        (local.set $kn (local.get $knr))))))
            (local.set $a (f64.mul (local.get $a) (local.get $kd)))
            (local.set $na (f64.mul (local.get $na) (local.get $kn)))
            (if (i32.and (i32.eqz (local.get $rel)) (f64.lt (local.get $a) (local.get $fl)))
              (then (local.set $a (local.get $fl))))
            (if (f64.lt (f64.add (local.get $a) (local.get $na)) (local.get $kill))
              (then (local.set $dead (i32.const 1)) (br $cexit)))
            (local.set $p1 (f64.add (local.get $p1) (local.get $d)))
            (if (f64.gt (local.get $p1) (local.get $tau))
              (then (local.set $p1 (f64.sub (local.get $p1) (local.get $tau)))))
            (local.set $p2 (f64.add (local.get $p2) (local.get $d2)))
            (if (f64.gt (local.get $p2) (local.get $tau))
              (then (local.set $p2 (f64.sub (local.get $p2) (local.get $tau)))))
            (local.set $p3 (f64.add (local.get $p3) (local.get $d3)))
            (if (f64.gt (local.get $p3) (local.get $tau))
              (then (local.set $p3 (f64.sub (local.get $p3) (local.get $tau)))))
            (local.set $p4 (f64.add (local.get $p4) (local.get $d4)))
            (if (f64.gt (local.get $p4) (local.get $tau))
              (then (local.set $p4 (f64.sub (local.get $p4) (local.get $tau)))))
            (local.set $t (call $sinw (local.get $p1)))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p2)) (f64.const 0.42))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p3)) (f64.const 0.16))))
            (local.set $t (f64.add (local.get $t) (f64.mul (call $sinw (local.get $p4)) (f64.const 0.23))))
            (local.set $y (f64.mul (local.get $t) (local.get $a)))
            (local.set $ad (i32.add (local.get $outl) (i32.shl (local.get $k) (i32.const 2))))
            (f32.store (local.get $ad)
              (f32.add (f32.load (local.get $ad)) (f32.demote_f64 (local.get $y))))
            (if (i32.ne (local.get $stereo) (i32.const 0))
              (then
                (local.set $ad (i32.add (local.get $outr) (i32.shl (local.get $k) (i32.const 2))))
                (f32.store (local.get $ad)
                  (f32.add (f32.load (local.get $ad))
                           (f32.demote_f64 (f64.mul (local.get $y) (f64.const 0.93)))))))
            (br $cloop)))
          ))
          ))
      ;; ============ state write-back ============
      (if (i32.ne (local.get $dead) (i32.const 0))
        (then (i32.store (local.get $c) (i32.const 0)))
        (else
          (f64.store (local.get $fb) (local.get $a))
          (f64.store (i32.add (local.get $fb) (i32.const 8)) (local.get $na))
          (f64.store (i32.add (local.get $fb) (i32.const 16)) (local.get $kd))
          (f64.store (i32.add (local.get $fb) (i32.const 24)) (local.get $kn))
          (f64.store (i32.add (local.get $fb) (i32.const 32)) (local.get $kr))
          (f64.store (i32.add (local.get $fb) (i32.const 40)) (local.get $knr))
          (f64.store (i32.add (local.get $fb) (i32.const 48)) (local.get $p1))
          (f64.store (i32.add (local.get $fb) (i32.const 56)) (local.get $p2))
          (f64.store (i32.add (local.get $fb) (i32.const 64)) (local.get $p3))
          (f64.store (i32.add (local.get $fb) (i32.const 72)) (local.get $p4))
          (f64.store (i32.add (local.get $fb) (i32.const 80)) (local.get $p5))
          (f64.store (i32.add (local.get $fb) (i32.const 88)) (local.get $p6))
          (f64.store (i32.add (local.get $fb) (i32.const 96)) (local.get $p7))
          (f64.store (i32.add (local.get $fb) (i32.const 120)) (local.get $g))
          (i32.store (i32.add (local.get $c) (i32.const 4)) (local.get $stv))
          (i32.store (i32.add (local.get $c) (i32.const 8)) (local.get $holdv)))
      )
      (br $voices)))
    (i32.store (local.get $seedp) (local.get $ns))
    (f64.store (local.get $nzp) (local.get $nzlp)))
  (export "sinw" (func $sinw)))
